name: CICD
on: [push]
jobs:
  check: 
    runs-on: ubuntu-latest
    steps:
      - name: check source code
        uses: actions/checkout@v3
      - name: install and run prettier check
        run:
          npm install
          npx prettier --check ./source
          
